name: LaTeX Compile Workflow

on:
  workflow_call:
    inputs:
      pdf_name:
        required: true
        type: string
        description: "The desired name of the output PDF (without the .pdf extension)"

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout caller repository and submodules
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex 

      - name: Rename PDF
        run: mv main.pdf ${{ inputs.pdf_name }}.pdf

      - name: Get current date
        id: date
        run: echo "today=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create New Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ steps.date.outputs.today }}.${{ github.run_number }}"
          name: "${{ inputs.pdf_name }} Update - ${{ steps.date.outputs.today }}"

          body: "Automated compile from commit ${{ github.sha }}"
          files: ${{ inputs.pdf_name }}.pdf

          make_latest: true